### PR TITLE
match quotes in example

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by jennybc** [comment]
I don't think this build error has anything to do with me fixing those quotes btw. The example doesn't work as is.

**Comment by jennybc** [comment]
Fixing these unbalanced quotes would be really nice. Everytime I run this example, I stumble over this.

**Comment by jimhester** [comment]
Thanks!

**Comment by jimhester** [comment]
Sorry I didn't merge this sooner, I somehow missed it.

**Pull request merged**
